// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx5u7J0-ozH6wl45FrDSKFaUrlUlxgR6o',
    appId: '1:284333516629:web:533a4877b7d51eb87ef1dc',
    messagingSenderId: '284333516629',
    projectId: 'todo-task-app-3d6b8',
    authDomain: 'todo-task-app-3d6b8.firebaseapp.com',
    storageBucket: 'todo-task-app-3d6b8.firebasestorage.app',
    measurementId: 'G-B4LWYE54D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oKdgufGICJJtQ05QJ_8KwiHwn77VOQw',
    appId: '1:284333516629:android:3388c2a154fc4d7a7ef1dc',
    messagingSenderId: '284333516629',
    projectId: 'todo-task-app-3d6b8',
    storageBucket: 'todo-task-app-3d6b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPyjwLD1loTrmRJo7qJl7c5Te78vmvBPU',
    appId: '1:284333516629:ios:c6f6bb2dfb4cf5637ef1dc',
    messagingSenderId: '284333516629',
    projectId: 'todo-task-app-3d6b8',
    storageBucket: 'todo-task-app-3d6b8.firebasestorage.app',
    iosBundleId: 'com.example.todoTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPyjwLD1loTrmRJo7qJl7c5Te78vmvBPU',
    appId: '1:284333516629:ios:c6f6bb2dfb4cf5637ef1dc',
    messagingSenderId: '284333516629',
    projectId: 'todo-task-app-3d6b8',
    storageBucket: 'todo-task-app-3d6b8.firebasestorage.app',
    iosBundleId: 'com.example.todoTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx5u7J0-ozH6wl45FrDSKFaUrlUlxgR6o',
    appId: '1:284333516629:web:8f6b66218adfa60d7ef1dc',
    messagingSenderId: '284333516629',
    projectId: 'todo-task-app-3d6b8',
    authDomain: 'todo-task-app-3d6b8.firebaseapp.com',
    storageBucket: 'todo-task-app-3d6b8.firebasestorage.app',
    measurementId: 'G-2CLQL8GTGE',
  );
}